// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace UnitService.Data.Database
{

    // People
    public class Person
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public string FirstName { get; set; } // FirstName
        public string LastName { get; set; } // LastName
        public System.DateTime DateOfBirth { get; set; } // DateOfBirth
        public System.Guid UnitId { get; set; } // UnitId

        // Foreign keys
        public virtual Unit Unit { get; set; } // FK_People_Units
        
        public Person()
        {
            Id = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
